services:
  api:
    image: api
    build:
      context: .
      dockerfile: BaseArchiCsharp.WebAPI/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=mydb;Username=api;Password=api_mdp"
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - networkApi
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api_mdp
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - networkApi

volumes:
    postgres_data:
networks:
    networkApi: